### ISSUE TITLE
Some sprites not transparent weird background effects

### ISSUE THREAD

**Issue by PascalHolscher** [jackrzhang/pokemon-gif#3]
Hello,

I'm using this library for a discord bot but I notice with some pokemon that the sprites glitch with parts of white in the background (feebas for example) is this a pokestadium bug or?
Hope to hear from you.

With kind regards,

Pascal

**Comment by jackrzhang** [comment]
Hi Pascal - this package just returns URLs for the sprites, so it shouldn't have any affect on the visual content for the sprites. Hope this helps!
